### PR TITLE
Add custom var lsp-php-server-development-checkout

### PR DESCRIPTION
**Pull request by NateEag**
I track the development version of the php-language-server and had been
using it with Emacs and my own unfinished lsp-php extension for a while.

With this change, I can use this package to do that.

It's useful if you want to keep up with the bleeding edge or if you want to actually hack on php-language-server yourself.

### CODE REVIEW

**Comment by NateEag** [comment]
@tszg Any chance you'll be able to take a look at this soon?

**Comment by tszg** [comment]
Sorry, late reply, now is our New Year, we are on holiday. Thank you for your contribution, but I think it may be more flexible to specify server startup mode directly. See the `develop` branch, and I hope you can give Suggestions or modifications to improve `lsp-php`.

**Comment by tszg** [comment]
@NateEag Sorry, wrong operation, branch merge error, you can pull the request again.

**Comment by NateEag** [comment]
No worries about the late reply.

If you want to do something more with my change, by all means feel free.

However, I'm looking at moving to [the backend the emacs-lsp org has started](https://github.com/emacs-lsp/lsp-php) and making further contributions to it, so I'm not going to do more with this PR at the moment.

Thanks for your work on this!

**Pull request merged**
